### ISSUE TITLE
about front view foreground segmentation gt ?

### ISSUE THREAD

**Issue by sgzqc** [leofansq/CBR#1]
thanks for your awesome work ,  i want to ask what is the meaning for the front view foreground segmentation ground truth?

**Comment by leofansq** [comment]
We choose to adopt the front view foreground segmentation as an auxiliary task for two main considerations:
1) It contributes to modeling the objects’ height (to the ground) distribution, which is important for infrastructure-side perception due to the mounting posture of infrastructure-side cameras. 
2) It enables the supervision of view decoupling to one of the standard views (front view), which is to deal with the various pitch angles. 

The groundtruth is generated according to bounding box labels via the projection to front view. It simulates a view of the traffic scene from a position below the infrastructure-side camera.
