### ISSUE TITLE
det_infer.py line261-line266

### ISSUE THREAD

**Issue by Ayanamiyui** [leofansq/CBR#2]
`xs = xs.view(
	batch, self.max_detection,
	1) * self.pc_range[4] / self.bev_map_size[0] + self.pc_range[0]
`
`ys = (self.bev_map_size[1]-ys.view(
	batch, self.max_detection,
	1)) * self.pc_range[4] / self.bev_map_size[1] + self.pc_range[1]`
为什么xs和ys都是*pc_range[4]呢。这段代码具体还原的是什么信息方便作者描述一下吗，万分感谢。

**Comment by leofansq** [comment]
Sorry for the confusing code. 
These two lines recover the location in pc from location in bev-map. Thus, it actually should be self.pc_range[4]-self.pc_range[1] and self.pc_range[3]-self.pc_range[0]. 
Since both of the two values are 90 ([-45.0, 0.0, -5.0, 45.0, 90.0, 5.0]), we directly use self.pc_range[4] here. 
We have update the code to the right one. Thanks for pointing out this :)
