### ISSUE TITLE
关于实验结果

### ISSUE THREAD

**Issue by enhance-yes** [leofansq/CBR#5]
你好，请问您实验结果的 AP11是什么意思呢
----------- AP11 Results ------------

Car AP11@0.70, 0.70, 0.70:
bev  AP11:24.5080, 21.3760, 21.2695
3d   AP11:1.8983, 1.7485, 1.7234
Car AP11@0.70, 0.50, 0.50:
bev  AP11:44.4519, 37.7136, 37.5894
3d   AP11:15.8948, 13.7651, 13.6353

----------- AP40 Results ------------

Car AP40@0.70, 0.70, 0.70:
bev  AP40:20.3321, 16.6847, 16.5142
3d   AP40:1.1903, 0.8891, 0.8730
Car AP40@0.70, 0.50, 0.50:
bev  AP40:42.4265, 35.0740, 34.9402
3d   AP40:13.5345, 11.1818, 11.0697

**Comment by leofansq** [comment]
AP11 and AP40 are the two commonly used evaluation metrics. AP11 uses 11 recall positions for AP calculation, which is proposed in the original Pascal VOC benchmark and used as a standard metric in KITTI before 08.10.2019. After that date, AP40 (uses 40 recall positions) is used in KITTI. We provided both of them in the code for research convenience, since some detection frameworks (like the previous version of MMdet3D) still utilize AP11 as a metric.
